In [21]:
import torch

tensor = torch.arange(1, 12, 2)
tensor

tensor([ 1,  3,  5,  7,  9, 11])

In [22]:
tensor.shape

torch.Size([6])

In [23]:
tensor.numel()

6

In [24]:
tensor = tensor.reshape(2, 3)

In [25]:
torch.exp(tensor)

tensor([[2.7183e+00, 2.0086e+01, 1.4841e+02],
        [1.0966e+03, 8.1031e+03, 5.9874e+04]])

In [26]:
tensor

tensor([[ 1,  3,  5],
        [ 7,  9, 11]])

In [28]:
t1 = tensor.reshape(1, 2, 3)
t2 = tensor.reshape(1, 2, 3)

In [33]:
torch.cat((t1, t2), dim=0).shape

torch.Size([2, 2, 3])

In [34]:
torch.cat((t1, t2), dim=1).shape

torch.Size([1, 4, 3])

In [35]:
torch.cat((t1, t2), dim=2).shape


torch.Size([1, 2, 6])

In [36]:
torch.cat((t1, t2), dim=3).shape

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

In [37]:
tensor

tensor([[ 1,  3,  5],
        [ 7,  9, 11]])

In [47]:
t1

tensor([[[-1, -1, -1],
         [ 7,  9, 11]]])

In [48]:
t1.sum()

tensor(24)

In [49]:
t1[0,1,1]=999

In [50]:
t1

tensor([[[ -1,  -1,  -1],
         [  7, 999,  11]]])

In [52]:
t3 = torch.zeros_like(t1)

In [54]:
print(id(t3))
t3=t1+t2
print(id(t3))

5730810752
5730391280
