In [29]:
import torch

tensor = torch.arange(1, 12, 2)
tensor

tensor([ 1,  3,  5,  7,  9, 11])

In [30]:
tensor.shape

torch.Size([6])

In [31]:
tensor.numel()

6

In [32]:
tensor = tensor.reshape(2, 3)

In [33]:
torch.exp(tensor)

tensor([[2.7183e+00, 2.0086e+01, 1.4841e+02],
        [1.0966e+03, 8.1031e+03, 5.9874e+04]])

In [34]:
tensor

tensor([[ 1,  3,  5],
        [ 7,  9, 11]])

In [35]:
t1 = tensor.reshape(1, 2, 3)
t2 = tensor.reshape(1, 2, 3)

In [36]:
torch.cat((t1, t2), dim=0).shape

torch.Size([2, 2, 3])

In [37]:
torch.cat((t1, t2), dim=1).shape

torch.Size([1, 4, 3])

In [38]:
torch.cat((t1, t2), dim=2).shape


torch.Size([1, 2, 6])

In [39]:
torch.cat((t1, t2), dim=2).shape

torch.Size([1, 2, 6])

In [40]:
tensor[:]=0

In [41]:
t1

tensor([[[0, 0, 0],
         [0, 0, 0]]])

In [42]:
t2

tensor([[[0, 0, 0],
         [0, 0, 0]]])

In [43]:
t1[0,1,1]=999

In [44]:
t1

tensor([[[  0,   0,   0],
         [  0, 999,   0]]])

In [45]:
t3 = torch.zeros_like(t1)

In [46]:
print(id(t3))
t3=t1+t2
print(id(t3))

6021143824
6021153472


In [47]:
t3 = torch.arange(12)
t4 = t3.reshape(2,6)
t5 = t3.reshape((2,6))

In [48]:
t5

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [49]:
t5.T==t5.T

tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True]])

In [54]:
a1 = torch.arange(9)
a1=a1.reshape(3,3)

In [59]:
a1[:]=1
a1[1,1]=2
a1[0,1]=3

In [60]:
a1==a1.T

tensor([[ True, False,  True],
        [False,  True,  True],
        [ True,  True,  True]])

In [61]:
s1 = torch.arange(12,dtype=torch.float32).reshape(3,4)

In [62]:
s1

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [63]:
s2 = s1.clone()

In [64]:
s3 = s1+s2

In [66]:
s1,s2,s3

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.]]))

In [67]:
s1[0,0]=10

In [69]:
id(s1),id(s2),id(s3)

(5986185024, 5989724544, 6021140784)

In [70]:
s4 = s1

In [71]:
id(s1),id(s4),id(s3)


(5986185024, 5986185024, 6021140784)

In [72]:
s1*s3

tensor([[  0.,   2.,   8.,  18.],
        [ 32.,  50.,  72.,  98.],
        [128., 162., 200., 242.]])

In [80]:
s1

tensor([[10.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [81]:
s1.sum(axis=[0])

tensor([22., 15., 18., 21.])

In [85]:
s1.mean(axis=[0])

tensor([7.3333, 5.0000, 6.0000, 7.0000])

In [95]:
s1.sum(axis=[0],keepdims=True),s1.sum(axis=[1],keepdims=True),

(tensor([[22., 15., 18., 21.]]),
 tensor([[16.],
         [22.],
         [38.]]))

In [96]:
s1/s1.sum(axis=[0],keepdims=True),s1/s1.sum(axis=[1],keepdims=True)

(tensor([[0.4545, 0.0667, 0.1111, 0.1429],
         [0.1818, 0.3333, 0.3333, 0.3333],
         [0.3636, 0.6000, 0.5556, 0.5238]]),
 tensor([[0.6250, 0.0625, 0.1250, 0.1875],
         [0.1818, 0.2273, 0.2727, 0.3182],
         [0.2105, 0.2368, 0.2632, 0.2895]]))

In [106]:
v1 = torch.arange(4,dtype=torch.float32)
torch.dot(v1,v1),v1*v1

(tensor(14.), tensor([0., 1., 4., 9.]))

In [114]:
torch.mv(s1,v1).shape

torch.Size([3])

In [112]:
s1[0,0]=0
torch.mm(s1,s2.T)

tensor([[ 14.,  38.,  62.],
        [ 38., 126., 214.],
        [ 62., 214., 366.]])

In [116]:
torch.norm(s1,keepdim=True),torch.norm(s1)


(tensor([[22.4944]]), tensor(22.4944))

In [117]:
torch.abs(s1).sum()

tensor(66.)

In [123]:
c1 = torch.arange(12).reshape(2,2,3)
c1

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [122]:
c1.sum(axis=[0])

tensor([[ 6,  8, 10],
        [12, 14, 16]])