In [1]:
import torch

tensor = torch.arange(1, 12, 2)
tensor

tensor([ 1,  3,  5,  7,  9, 11])

In [2]:
tensor.shape

torch.Size([6])

In [3]:
tensor.numel()

6

In [4]:
tensor = tensor.reshape(2, 3)

In [5]:
torch.exp(tensor)

tensor([[2.7183e+00, 2.0086e+01, 1.4841e+02],
        [1.0966e+03, 8.1031e+03, 5.9874e+04]])

In [6]:
tensor

tensor([[ 1,  3,  5],
        [ 7,  9, 11]])

In [7]:
t1 = tensor.reshape(1, 2, 3)
t2 = tensor.reshape(1, 2, 3)

In [8]:
torch.cat((t1, t2), dim=0).shape

torch.Size([2, 2, 3])

In [9]:
torch.cat((t1, t2), dim=1).shape

torch.Size([1, 4, 3])

In [10]:
torch.cat((t1, t2), dim=2).shape


torch.Size([1, 2, 6])

In [12]:
torch.cat((t1, t2), dim=2).shape

torch.Size([1, 2, 6])

In [14]:
tensor[:]=0

In [15]:
t1

tensor([[[0, 0, 0],
         [0, 0, 0]]])

In [16]:
t2

tensor([[[0, 0, 0],
         [0, 0, 0]]])

In [ ]:
t1[0,1,1]=999

In [ ]:
t1

In [ ]:
t3 = torch.zeros_like(t1)

In [ ]:
print(id(t3))
t3=t1+t2
print(id(t3))

In [18]:
t3 = torch.arange(12)
t4 = t3.reshape(2,6)
t5 = t3.reshape((2,6))

In [19]:
t4==t5

tensor([[True, True, True, True, True, True],
        [True, True, True, True, True, True]])