In [29]:
import torch

tensor = torch.arange(1, 12, 2)
tensor

tensor([ 1,  3,  5,  7,  9, 11])

In [30]:
tensor.shape

torch.Size([6])

In [31]:
tensor.numel()

6

In [32]:
tensor = tensor.reshape(2, 3)

In [33]:
torch.exp(tensor)

tensor([[2.7183e+00, 2.0086e+01, 1.4841e+02],
        [1.0966e+03, 8.1031e+03, 5.9874e+04]])

In [34]:
tensor

tensor([[ 1,  3,  5],
        [ 7,  9, 11]])

In [35]:
t1 = tensor.reshape(1, 2, 3)
t2 = tensor.reshape(1, 2, 3)

In [36]:
torch.cat((t1, t2), dim=0).shape

torch.Size([2, 2, 3])

In [37]:
torch.cat((t1, t2), dim=1).shape

torch.Size([1, 4, 3])

In [38]:
torch.cat((t1, t2), dim=2).shape


torch.Size([1, 2, 6])

In [39]:
torch.cat((t1, t2), dim=2).shape

torch.Size([1, 2, 6])

In [40]:
tensor[:]=0

In [41]:
t1

tensor([[[0, 0, 0],
         [0, 0, 0]]])

In [42]:
t2

tensor([[[0, 0, 0],
         [0, 0, 0]]])

In [43]:
t1[0,1,1]=999

In [44]:
t1

tensor([[[  0,   0,   0],
         [  0, 999,   0]]])

In [45]:
t3 = torch.zeros_like(t1)

In [46]:
print(id(t3))
t3=t1+t2
print(id(t3))

6021143824
6021153472


In [47]:
t3 = torch.arange(12)
t4 = t3.reshape(2,6)
t5 = t3.reshape((2,6))

In [48]:
t5

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [49]:
t5.T==t5.T

tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True]])

In [54]:
a1 = torch.arange(9)
a1=a1.reshape(3,3)

In [59]:
a1[:]=1
a1[1,1]=2
a1[0,1]=3

In [60]:
a1==a1.T

tensor([[ True, False,  True],
        [False,  True,  True],
        [ True,  True,  True]])